config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :name, presence: true
    validates :comment, length: {maximum: 140},
                        presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :content, length: {minimum: 50},
                        presence: true
    validates :title, length: {maximum: 50},
                        presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "akshaya", password:"Sourajaks#98", except: [:create]
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
        redirect_to post_path(@post)
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "akshaya", password:"Sourajaks#98", except: [:index, :show]
    def index
        @posts = Post.all.order("created_at DESC")
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create(post_params)
        if @post
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def edit
        @post = Post.find(params[:id])
        
    end

    def destroy
        @post = Post.find(params[:id]) 
        @post.destroy 

        redirect_to posts_path
    end

    private

    def post_params
        params.require(:post).permit(:title, :content)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong><%= comment.name %></strong>
                    <%= comment.comment %>
                </p>
            </div>
        </div>

        <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?"} %>
    </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f|%>
    <div class="field">
        <div class ="control">
            <%= f.input :name, input_html: {class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <div class="field">
        <div class ="control">
            <%= f.input :comment, input_html: {class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Home', root_path, class: "navbar-item" %>
            </div>
            <div class="navbar-brand">
              <%= link_to 'About', static_pages_about_path, class: "navbar-item" %>
            </div>
            <div class="navbar-brand">
              <%= link_to 'Blogs', posts_path, class: "navbar-item" %>
            </div>
            <div class="navbar-brand">
              <%= link_to 'Help/Contact', static_pages_help_path, class: "navbar-item" %>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to "Create New Post", new_post_path, class: "navbar-item" %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
    <%= simple_form_for @post do |f| %>
    <div class="field">
        <div class ="control">
            <%= f.input :title, input_html: {class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <div class="field">
        <div class ="control">
            <%= f.input :content, input_html: {class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
    <%end%>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>



<section class="section">
    <div class="container">
        <% @posts.each do |post| %>
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="is-4" ><strong><%= link_to post.title, post %></strong></p>
                        </div>
                    </div>
                    <div class="content">
                        <%= post.content %>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create New Post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section" >
    <div class="container">
        <nav class="level">
            <div class="level-left">
                <p class"level-item">
                    <strong>Actions</strong>
                </p>
            </div>  

            <div class="level-right">
                <p class"level-item">
                    <%= link_to "Edit", edit_post_path(@post), class: "button" %>
                </p>
                <p class"level-item">
                    <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure? "}, class: "button is-danger" %>
                </p>
                
            </div>   
        </nav>
        <hr />

        <div class="content">
            <%= @post.content %>
        </div>
    </div>
</section>

<section class="comments">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
            <%= render 'comments/form' %>
        </div>
    </div>
</section>

app/views/static_pages/about.html.erb
<% content_for :page_title, "About Me!" %>
<p>Name : Akshaya Rajagopalan</p>

app/views/static_pages/help.html.erb
<% content_for :page_title, "Help And Contact" %>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% content_for :page_title, "10 Reasons Why Writing blogs is Relaxing" %>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>